services:
  - type: web
    name: havuc-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: AIzaSyAIofeO0UnMLoWsDSBGE-yKdLz5sBZzawM
        sync: false
      - key: SECRET_KEY
        generateValue: true




