services:
  - type: web
    name: havuc-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: AIzaSyDGDmQd3f3U0F-yNQL9PZ-3ckyME-sHzzU
        sync: false
      - key: SECRET_KEY
        generateValue: true

